### PR TITLE
Created a landpage

### PR DESCRIPTION
**Pull request by priyanshu-gupta0503**
created an aestheic landing page using html and css and took inspiration from figma

### CODE REVIEW

**Review by Sayed-Afnan-Khazi — CHANGES_REQUESTED** [review]
Looks great!
Could you please make the page responsive? We want to make sure that anyone on any device can have a look at the HDU website.

**Comment by priyanshu-gupta0503** [comment]
heY@ Sayed-Afnan-Khazi  I have updated the pull request by adding responsiveness  to the landing page

**Comment by priyanshu-gupta0503** [comment]
I have added responsiveness pls check my PR



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/09/23,
08:03:32 PM

**Comment by priyanshu-gupta0503** [comment]
Hi Gdsc-Jssstu/Hdu-University-Website pls seemy PR I have added
responsiveness and now it is working fine .

**Pull request merged**
